# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "chat.baml": "function ChatReply(message: string) -> string {\n  client \"GeminiDefault\"\n  prompt #\"\n    You are a helpful assistant.\n    {{ ctx.output_format }}\n\n    USER:\n    {{ message }}\n  \"#\n}\n",
    "clients.baml": "client<llm> GeminiDefault {\n  provider google-ai\n  options {\n    model \"gemini-2.5-flash-lite\"\n  }\n}\n",
}

def get_baml_files():
    return _file_map