# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class MemoriesStore(BaseModel):
    description: typing.Optional[str] = None
    image_index: typing.Optional[int] = None

class Report(BaseModel):
    overall_assessment: typing.Optional[str] = None
    risk_level: typing.Optional[types.RiskLevel] = None
    key_concerns: typing.List[str]
    symptoms: typing.List["Symptom"]
    protective_factors: typing.List[str]
    functional_impact: typing.Optional[str] = None
    recommended_clinical_focus: typing.Optional[str] = None
    limitations: typing.Optional[str] = None

class SelectMemoryResponse(BaseModel):
    selected_memories_summary: typing.Optional[str] = None
    image_index_list: typing.List[int]

class Symptom(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    evidence_from_messages: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
