# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ChatReply(self, message: str,conversation_history: typing.List[str],sentiment: str,memory: str,escalate_message: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ChatReply(message=message,conversation_history=conversation_history,sentiment=sentiment,memory=memory,escalate_message=escalate_message,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ChatReply", args={
                "message": message,"conversation_history": conversation_history,"sentiment": sentiment,"memory": memory,"escalate_message": escalate_message,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateClinicalReportHtml(self, clinical_report_json: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GenerateClinicalReportHtml(clinical_report_json=clinical_report_json,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateClinicalReportHtml", args={
                "clinical_report_json": clinical_report_json,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateReport(self, message_history: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Report:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GenerateReport(message_history=message_history,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateReport", args={
                "message_history": message_history,
            })
            return typing.cast(types.Report, result.cast_to(types, types, stream_types, False, __runtime__))
    def ImageDescription(self, image_b64: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ImageDescription(image_b64=image_b64,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ImageDescription", args={
                "image_b64": image_b64,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def SelectMemory(self, query: str,memories_store: typing.List["types.MemoriesStore"],
        baml_options: BamlCallOptions = {},
    ) -> types.SelectMemoryResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.SelectMemory(query=query,memories_store=memories_store,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="SelectMemory", args={
                "query": query,"memories_store": memories_store,
            })
            return typing.cast(types.SelectMemoryResponse, result.cast_to(types, types, stream_types, False, __runtime__))
    def SentimentAnalysis(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.SentimentAnalysis(user_message=user_message,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="SentimentAnalysis", args={
                "user_message": user_message,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def TrustedContact(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> bool:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.TrustedContact(query=query,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="TrustedContact", args={
                "query": query,
            })
            return typing.cast(bool, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatReply(self, message: str,conversation_history: typing.List[str],sentiment: str,memory: str,escalate_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ChatReply", args={
            "message": message,"conversation_history": conversation_history,"sentiment": sentiment,"memory": memory,"escalate_message": escalate_message,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateClinicalReportHtml(self, clinical_report_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateClinicalReportHtml", args={
            "clinical_report_json": clinical_report_json,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateReport(self, message_history: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Report, types.Report]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateReport", args={
            "message_history": message_history,
        })
        return baml_py.BamlSyncStream[stream_types.Report, types.Report](
          result,
          lambda x: typing.cast(stream_types.Report, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Report, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ImageDescription(self, image_b64: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ImageDescription", args={
            "image_b64": image_b64,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def SelectMemory(self, query: str,memories_store: typing.List["types.MemoriesStore"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SelectMemoryResponse, types.SelectMemoryResponse]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="SelectMemory", args={
            "query": query,"memories_store": memories_store,
        })
        return baml_py.BamlSyncStream[stream_types.SelectMemoryResponse, types.SelectMemoryResponse](
          result,
          lambda x: typing.cast(stream_types.SelectMemoryResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SelectMemoryResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def SentimentAnalysis(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="SentimentAnalysis", args={
            "user_message": user_message,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def TrustedContact(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[bool, bool]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="TrustedContact", args={
            "query": query,
        })
        return baml_py.BamlSyncStream[bool, bool](
          result,
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatReply(self, message: str,conversation_history: typing.List[str],sentiment: str,memory: str,escalate_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ChatReply", args={
            "message": message,"conversation_history": conversation_history,"sentiment": sentiment,"memory": memory,"escalate_message": escalate_message,
        }, mode="request")
        return result
    def GenerateClinicalReportHtml(self, clinical_report_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateClinicalReportHtml", args={
            "clinical_report_json": clinical_report_json,
        }, mode="request")
        return result
    def GenerateReport(self, message_history: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateReport", args={
            "message_history": message_history,
        }, mode="request")
        return result
    def ImageDescription(self, image_b64: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ImageDescription", args={
            "image_b64": image_b64,
        }, mode="request")
        return result
    def SelectMemory(self, query: str,memories_store: typing.List["types.MemoriesStore"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SelectMemory", args={
            "query": query,"memories_store": memories_store,
        }, mode="request")
        return result
    def SentimentAnalysis(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SentimentAnalysis", args={
            "user_message": user_message,
        }, mode="request")
        return result
    def TrustedContact(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TrustedContact", args={
            "query": query,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatReply(self, message: str,conversation_history: typing.List[str],sentiment: str,memory: str,escalate_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ChatReply", args={
            "message": message,"conversation_history": conversation_history,"sentiment": sentiment,"memory": memory,"escalate_message": escalate_message,
        }, mode="stream")
        return result
    def GenerateClinicalReportHtml(self, clinical_report_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateClinicalReportHtml", args={
            "clinical_report_json": clinical_report_json,
        }, mode="stream")
        return result
    def GenerateReport(self, message_history: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateReport", args={
            "message_history": message_history,
        }, mode="stream")
        return result
    def ImageDescription(self, image_b64: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ImageDescription", args={
            "image_b64": image_b64,
        }, mode="stream")
        return result
    def SelectMemory(self, query: str,memories_store: typing.List["types.MemoriesStore"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SelectMemory", args={
            "query": query,"memories_store": memories_store,
        }, mode="stream")
        return result
    def SentimentAnalysis(self, user_message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SentimentAnalysis", args={
            "user_message": user_message,
        }, mode="stream")
        return result
    def TrustedContact(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="TrustedContact", args={
            "query": query,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))