# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class RiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    EMERGENCY = "EMERGENCY"

# #########################################################################
# Generated classes (4)
# #########################################################################

class MemoriesStore(BaseModel):
    description: str
    image_index: int

class Report(BaseModel):
    overall_assessment: str
    risk_level: RiskLevel
    key_concerns: typing.List[str]
    symptoms: typing.List["Symptom"]
    protective_factors: typing.List[str]
    functional_impact: str
    recommended_clinical_focus: str
    limitations: str

class SelectMemoryResponse(BaseModel):
    selected_memories_summary: str
    image_index_list: typing.List[int]

class Symptom(BaseModel):
    name: str
    description: str
    evidence_from_messages: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
